### ISSUE TITLE
Detect install from git vs npm vs local

### ISSUE THREAD

**Issue by Efreak** [indexzero/node-pkginfo#14]
Is there any way to do this? I've looked at package.json for a package I installed from a git repo, and it appears to have the same information in it as a package installed from git does.

**Comment by indexzero** [comment]
1. It will be a git repo if there is a `.git` folder in it
2. It will be local if it is a symlink (see: [fs docs](https://nodejs.org/api/fs.html#fs_class_fs_stats)
3. Otherwise, it is installed from `npm`
